#!/bin/bash
#  Setup versions for image components
#  This script should be sourced by the other scripts
SYSLINUX=syslinux-6.03
BUILDROOT=https://github.com/buildroot/buildroot.git
BUILDROOT_TAG=2017.05.1
